version: "3.8"
services:
  web:
    build: ./view
    ports:
      - "8080:80"
      - "443:443"
    links:
      - server
  server:
    build: ./server
    ports:
      - "5000:5000"
  certbot:
    image: certbot/certbot
    container_name: certbot